#observação esse container foi executado em uma maquina virtual com o ip 192.168.20.4

version: '3.8'
services:
  rabbitmq:
    image: bitnami/rabbitmq:latest
    ports:
      - 5672:5672 # porta para a comunicação AMQP
      - 8080:15672 # porta para a interface web de gerenciamento
    environment:
      RABBITMQ_USERNAME: manager
      RABBITMQ_PASSWORD: 1234
      RABBITMQ_USERNAMES: Consumer,Producer # cria os usuários consumer e producer
      RABBITMQ_PASSWORDS: 1234,1234 # define as senhas dos usuários