version: '3.8'
services:
  rabbitmq:
    image: bitnami/rabbitmq:latest
    ports:
      - 5672:5672 # porta para a comunicação AMQP
      - 8080:15672 # porta para a interface web de gerenciamento
    environment:
      RABBITMQ_USERNAME: manager
      RABBITMQ_PASSWORD: 1234
